# Header
logo_text: # Add text logo instead of logo image

menu:
  Home: /
  Archives: archives
  About: about

# Content
excerpt_link: Read More
toc: true
fancybox: true

#comments
#disqus_shortname: your-shortname

# Miscellaneous
#google_analytics:
favicon: /css/images/logo.png

